name: Deploy to Ubuntu Server

on: push

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

      - name: Deploy via SSH
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST '
            set -e
            if [ ! -d ~/monitoring ]; then
              git clone git@github.com:Satoms-rep/monitoring.git ~/monitoring
            else
              cd ~/monitoring
              git pull
            fi
            cd ~/monitoring
            docker-compose pull
            docker-compose up -d
          '